### ISSUE TITLE
OnPress with Flex style create inconsistent results.

### ISSUE THREAD

**Issue by Bowman74** [kodefox/react-native-flex-image#1]
Consider the following:
`<View style={{flexDirection: 'row', backgroundColor: 'blue', justifyContent: 'space-between', alignItems: 'center'}}>
    <FlexImage source={require('../images/IconTwitter.png')} style={{flex: .2}}  />
</View>`

This control will size itself as expected. However, the problem appears if I change it to this:

`<View style={{flexDirection: 'row', backgroundColor: 'blue', justifyContent: 'space-between', alignItems: 'center'}}>
    <FlexImage source={require('../images/IconTwitter.png')} style={{flex: .2}} onPress={this._someOnpressMethod} />
</View>`

If this is used the image will be a completely different (smaller) size. This is because adding the onPress event handler surrounds the control with a TouchableOpacity and then the style={{flex: .2}} applies to that as the parent instead of the parent view in my code.

As a workaround I was able to use this code and get the expected results:
`<View style={{flexDirection: 'row', backgroundColor: 'blue', justifyContent: 'space-between', alignItems: 'center'}}>
    <TouchableOpacity style={{flex: .2}} onPress={this._someOnpressMethod}>
        <FlexImage source={require('../images/IconTwitter.png')}  />
    </TouchableOpacity>
</View>`

**Comment by oshimayoan** [comment]
Hi @Bowman74, I just made a diff for fixing this issue. If you have time, could you help to test it out?

Thanks.
